spring.application.name=ltw2-project
server.port=8081

spring.data.mongodb.host=mongodb
spring.data.mongodb.uri=mongodb+srv://tranquocdong102:uIFYTUJ9naAOZEKe@cluster0.s51on.mongodb.net/ltw2_project
spring.data.mongodb.database=ltw2_project

logging.level.org.springframework.web=DEBUG
# JWT
app.jwt.secret=${JWT_SECRET:yN4xQfT8gV1aR9pK2zXbM6wJ0cH5uE3L}
app.jwt.expiration-ms=86400000
