spring.application.name=ltw2-project
server.port=8081
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.data.mongodb.host=mongodb
spring.data.mongodb.uri=mongodb+srv://tranquocdong102:uIFYTUJ9naAOZEKe@cluster0.s51on.mongodb.net/ltw2_project
spring.data.mongodb.database=ltw2_project

logging.level.org.springframework.web=DEBUG
# JWT
app.jwt.secret=${JWT_SECRET:yN4xQfT8gV1aR9pK2zXbM6wJ0cH5uE3L}
app.jwt.expiration-ms=86400000

# ==== SMTP GMAIL CONFIG ====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tranquocdong10.2@gmail.com
spring.mail.password=lkkg ilan yexf cugk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==== BASE URL để sinh link ====
app.frontend.base-url=http://localhost:3000

